version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: circleci/python:3.10

    steps:
      - checkout
      - run: pip install telebot pymongo aiohttp
      - run: lscpu
      - run: chmod +x *
      - run: python3 God.py
      - run: |
          while true
          do
            sleep 600 # 10 minute ke baad restart
            echo "Restarting workflow..."
            exit 0
          done

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build-and-deploy
